language: erlang

otp_release:
 - 17.4
 - 17.3

env:
 - TASK=lint
 - TASK=node
 - TASK=server
 - TASK=validate-examples
 - TASK=error-messages

matrix:
 exclude:
  - otp_release: 17.3
    env: TASK=lint

script:
 - case "$TASK" in
     lint) sudo pip install -r requirements.txt && sudo pip install pyflakes && ./bin/lint.py . ;;
     validate-examples) sudo pip install -r requirements.txt && make -C examples check;;
     error-messages) sudo pip install -r requirements.txt && make -C invalid_examples check;;
     *) make -C $TASK check;;
   esac