language: erlang

otp_release:
 - 17.4
 - 17.3

env:
 - TASK=lint
 - TASK=node
 - TASK=server
 - TASK=validate-examples

matrix:
 exclude:
  - otp_release: 17.3
    env: TASK=lint

script:
 - case "$TASK" in
     lint) pip install --user pyflakes && $HOME/.local/bin/pyflakes ./**/*.py;;
     validate-examples) sudo pip install -r requirements.txt && make -C examples check;;
     *) make -C $TASK check;;
   esac